# OCF staff groups can administer CUPS (populated via LDAP)
SystemGroup ocfstaff opstaff

# TLS certificate (provided by ocf.acme)
ServerCertificate /var/lib/acme/@hostname@/fullchain.pem
ServerKey /var/lib/acme/@hostname@/key.pem

ConfigFilePerm 0644
LogFilePerm 0644
