name: Automated Deploy

on:
  workflow_run:
    workflows:
      - Build Hosts
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ci-ocf-nix-deploy
    steps:
      - uses: actions/checkout@v4
      - uses: ./composite/setup-hosts.yml
      - name: Deploy with colmena
        env:
          SSH_CONFIG_FILE: ${{ github.workspace }}/ssh_config
        run: |
          echo "$HOSTS" | tr ' ' '\n' | \
          xargs -P 10 -n 1 -I {} \
          nix develop .#deploy -c sh -c "
            # wait for host to be online with a timeout of 5s per attempt and 12
            # total tries, but fail immediately if the error is auth related
            if ! ssh -F \$SSH_CONFIG_FILE \
                     -o BatchMode=yes \
                     -o ConnectTimeout=5 \
                     -o ConnectionAttempts=12 \
                     {} echo 'continuous deployment ping!' > {}.log 2>&1; then
              echo '❌ Failed to deploy to {} (ssh timeout)'
              echo 'FAILURE:{}' >> results.txt
              exit
            fi

            if colmena apply --on {} switch > {}.log 2>&1; then
              echo '✅ Successfully deployed to {}'
              echo 'SUCCESS:{}' >> results.txt
            else
              echo '❌ Failed to deploy to {}'
              echo 'FAILURE:{}' >> results.txt
            fi
          "

      - name: Display successful logs
        if: always()
        run: |
          grep "SUCCESS:" results.txt | cut -d':' -f2 | while read host; do
            echo "--- $host ---"
            cat "${host}.log"
          done

      - name: Display failed logs
        if: always()
        run: |
          grep "FAILURE:" results.txt | cut -d':' -f2 | while read host; do
            echo "--- $host ---"
            cat "${host}.log"
          done

      - name: Check status
        if: always()
        run: |
          if grep -q "FAILURE:" results.txt; then
            exit 1
          fi
